### ISSUE TITLE
Custom Console deprecation warning

### ISSUE THREAD

**Issue by majksner** [rails-on-services/apartment#37]
```ruby
warning: setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead
```
* Rails (or ActiveRecord) version: 6.0.2.2

* Ruby version: 2.7.1

**Comment by rpbaltazar** [comment]
Resolved with #38

**Comment by majksner** [comment]
I'm still getting deprecation message using development branch

```
/var/www/app/shared/bundle/ruby/2.7.0/bundler/gems/apartment-a0d5ce582d16/lib/apartment/custom_console.rb:23: warning: `Pry::Prompt[:ros][:value]` is deprecated. Use `Pry::Prompt#prompt_procs` instead or an instance of `Pry::Prompt` directly
```

**Comment by rpbaltazar** [comment]
Ok. Will look into the issue

**Comment by rpbaltazar** [comment]
Which version of pry do you have installed?

**Comment by majksner** [comment]
```
❯ bundle info pry
  * pry (0.13.1)
	Summary: A runtime developer console and IRB alternative with powerful introspection capabilities.
	Homepage: http://pry.github.io
```

**Comment by rpbaltazar** [comment]
I just released a new version that fixes it. Please give it a try and let me know if you run against any issues
